-----INSERT USUARIO_ENTRENADOR-------
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Alejandro' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pedro' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Ana' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Alejandra' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Maria' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Azucena' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO USUARIO_ENTRENADOR VALUES ((SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Julia' LIMIT 1));


-----INSERT RESERVA-------
INSERT INTO RESERVA VALUES (default,TO_DATE('20/11/2017 08:30', 'DD/MM/YYYY HH:MI'),TO_DATE('20/11/2017', 'DD/MM/YYYY HH:MI 09:30'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Alejandro' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('21/11/2017 10:00', 'DD/MM/YYYY HH:MI'),TO_DATE('21/11/2017', 'DD/MM/YYYY HH:MI 12:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Alejandro' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('22/11/2017 07:30', 'DD/MM/YYYY HH:MI'),TO_DATE('22/11/2017', 'DD/MM/YYYY HH:MI 10:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pedro' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('23/11/2017 18:00', 'DD/MM/YYYY HH:MI'),TO_DATE('23/11/2017', 'DD/MM/YYYY HH:MI 20:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pedro' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('24/11/2017 09:00', 'DD/MM/YYYY HH:MI'),TO_DATE('24/11/2017', 'DD/MM/YYYY HH:MI 10:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pedro' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('25/11/2017 10:00', 'DD/MM/YYYY HH:MI'),TO_DATE('25/11/2017', 'DD/MM/YYYY HH:MI 13:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('26/11/2017 15:00', 'DD/MM/YYYY HH:MI'),TO_DATE('26/11/2017', 'DD/MM/YYYY HH:MI 17:30'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('27/11/2017 10:00', 'DD/MM/YYYY HH:MI'),TO_DATE('27/11/2017', 'DD/MM/YYYY HH:MI 11:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('28/11/2017 14:00', 'DD/MM/YYYY HH:MI'),TO_DATE('28/11/2017', 'DD/MM/YYYY HH:MI 17:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Maria' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('29/11/2017 16:30', 'DD/MM/YYYY HH:MI'),TO_DATE('29/11/2017', 'DD/MM/YYYY HH:MI 18:30'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Maria' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('30/11/2017 09:30', 'DD/MM/YYYY HH:MI'),TO_DATE('30/11/2017', 'DD/MM/YYYY HH:MI 10:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('20/11/2017 08:30', 'DD/MM/YYYY HH:MI'),TO_DATE('20/11/2017', 'DD/MM/YYYY HH:MI 09:30'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('21/11/2017 10:00', 'DD/MM/YYYY HH:MI'),TO_DATE('21/11/2017', 'DD/MM/YYYY HH:MI 12:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('22/11/2017 07:30', 'DD/MM/YYYY HH:MI'),TO_DATE('22/11/2017', 'DD/MM/YYYY HH:MI 10:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO RESERVA VALUES (default,TO_DATE('23/11/2017 18:00', 'DD/MM/YYYY HH:MI'),TO_DATE('23/11/2017', 'DD/MM/YYYY HH:MI 20:00'),(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Azucena' LIMIT 1));

-----INSERT MENSAJE-------
INSERT INTO MENSAJE VALUES (default,'hola, por que no viniste a clases?',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Alejandro' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Te asigne la rutina de hoy',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Alejandro' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Sigue trabajando asi',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Alexander' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pedro' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Acuerdate del pago',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Hoy te traje las proteinas, cuando puedas las buscas',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Te sugiero meterte a la clase de spinning',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Pedro' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Jorge' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Te evalue la rutina, sigue asi!',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Estoy vendiendo proteinas',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Vendo guantes y calleras',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));
INSERT INTO MENSAJE VALUES (default,'Este es el mensaje de prueba #10',(SELECT USU_ID FROM USUARIO WHERE USU_NOMBRE = 'Maria' LIMIT 1),(SELECT ENT_ID FROM ENTRENADOR WHERE ENT_NOMBRE = 'Pablo' LIMIT 1));

-----INSERT PROGRESO RUTINA-------
INSERT INTO PROGRESO_RUTINA VALUES (default,'PROGRESO NOTABLE', 'RUTINA DE PIERNAS',(SELECT RUT_ID FROM RUTINA WHERE RUT_NOMBRE = 'Piernas' LIMIT 1));
INSERT INTO PROGRESO_RUTINA VALUES (default,'PROGRESO MEDIO', 'RUTINA DE PIERNAS',(SELECT RUT_ID FROM RUTINA WHERE RUT_NOMBRE = 'Piernas' LIMIT 1));
INSERT INTO PROGRESO_RUTINA VALUES (default,'PROGRESO ESPERADO', 'RUTINA DE PIERNAS',(SELECT RUT_ID FROM RUTINA WHERE RUT_NOMBRE = 'Piernas' LIMIT 1));
INSERT INTO PROGRESO_RUTINA VALUES (default,'PROGRESO BAJO', 'RUTINA DE BICEPS',(SELECT RUT_ID FROM RUTINA WHERE RUT_NOMBRE = 'Biceps' LIMIT 1));
INSERT INTO PROGRESO_RUTINA VALUES (default,'NO HUBO PROGRESO', 'RUTINA DE BICEPS',(SELECT RUT_ID FROM RUTINA WHERE RUT_NOMBRE = 'Biceps' LIMIT 1));